# Generated by Django 4.2 on 2023-04-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PachisApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Local',
        ),
    ]
